### ISSUE TITLE
Feedback test :)

### ISSUE THREAD

**Issue by jenkuntz** [MicrosoftDocs/msftdynamicsgpdocs#12]
Just testing. The last sentence of the first paragraph sounds awkward starting with "But". "But we have started moving some of the existing content...". I would remove the but, as the rest of the sentence works without it and it flows much better for the reader.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aa4266d-d435-bdca-0db4-7a77bb2837de
* Version Independent ID: 5bf0b00c-5928-8921-0d20-459e2c615ca9
* Content: [Welcome to Dynamics GP - Dynamics GP](https://docs.microsoft.com/en-us/dynamics-gp/)
* Content Source: [dynamics-gp/index.md](https://github.com/MicrosoftDocs/msftdynamicsgpdocs/blob/live/dynamics-gp/index.md)
* Product: **dynamicsgp**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Jen, and thanks for submitting the first Issue! We really do value contributions to make this content better reflect Dynamics 2018 R2.

That's valid feedback, and I'll get it clarified.

**Comment by edupont04** [comment]
The change has been published. Closing issue.
