### ISSUE TITLE
Instructions to install certificate are not complete

### ISSUE THREAD

**Issue by tsyork** [MicrosoftDocs/msftdynamicsgpdocs#166]
Steps 9-14 in the Install Certificate section are a repeat of steps 3-8. The steps to actually install the certificate are not listed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2273e44b-4813-2bbe-4cd2-41afa2fd3f62
* Version Independent ID: 15d43124-e59b-b838-f1d4-08d958aabf79
* Content: [Importing certificates - Dynamics GP](https://docs.microsoft.com/en-us/dynamics-gp/web-components/importing-a-self-signed-security-certificate#feedback)
* Content Source: [dynamics-gp/web-components/importing-a-self-signed-security-certificate.md](https://github.com/MicrosoftDocs/msftdynamicsgpdocs/blob/live/dynamics-gp/web-components/importing-a-self-signed-security-certificate.md)
* Product: **dynamics-gp**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello tsyork,

Thank you for your feedback! This has now been updated.
