### ISSUE TITLE
More specifics on the Update 1099 Utility

### ISSUE THREAD

**Issue by dbegrmanTN** [MicrosoftDocs/msftdynamicsgpdocs#219]
Can you please be more specific on the Update 1099 Information?  
1. Do we update Vendor, 1099 or both
2. Do we need a range of vendors or will it only update those with that particular tax type and box number?
3. Do we need to just move the 2020 date range?
4. What happens if we need to re-generate a prior year 1099-MISC?
5. Do you suggest to print all prior year 1099-MISC with box 7 to a .pdf file before running the update?

These are questions I will be getting from GP customers.

Thanks,
Deb Bergman
Arctic IT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f210fc2-711b-07bb-e021-9d588f792e02
* Version Independent ID: 94e5955f-806e-eb98-c6ce-a4309df9e84c
* Content: [Form 1099 NEC - Dynamics GP](https://docs.microsoft.com/en-us/dynamics-gp/whats-new/form-1099-nec-now-supported)
* Content Source: [dynamics-gp/whats-new/form-1099-nec-now-supported.md](https://github.com/MicrosoftDocs/msftdynamicsgpdocs/blob/live/dynamics-gp/whats-new/form-1099-nec-now-supported.md)
* Product: **dynamics-gp**
* GitHub Login: @theley502
* Microsoft Alias: **theley**

**Comment by jswymer** [comment]
Thanks for the feedback! This has been addressed in the help.
