### ISSUE TITLE
page information is incorrect based on actual usage.

### ISSUE THREAD

**Issue by jland555** [MicrosoftDocs/msftdynamicsgpdocs#231]
This page shows that the layout should include the vendor ID in the first column.  However, in use, the first column is the distribution.  You can't paste without entering the vendor ID first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f28e3eb-a698-1d38-6f40-a70ca60358ae
* Version Independent ID: fa84b2cc-b50d-a527-bd5d-e3d37ba12451
* Content: [Copy/Paste Purchasing transactions from Excel - Dynamics GP](https://docs.microsoft.com/en-us/dynamics-gp/whats-new/copypaste-purchasing-transactions-from-excel)
* Content Source: [dynamics-gp/whats-new/copypaste-purchasing-transactions-from-excel.md](https://github.com/MicrosoftDocs/msftdynamicsgpdocs/blob/live/dynamics-gp/whats-new/copypaste-purchasing-transactions-from-excel.md)
* Product: **dynamics-gp**
* GitHub Login: @theley502
* Microsoft Alias: **theley**

**Comment by jswymer** [comment]
Thanks for the feedback! This has been addressed in the help.
