### ISSUE TITLE
TenantConfiguration.xml file location is incorrect

### ISSUE THREAD

**Issue by crexin** [MicrosoftDocs/msftdynamicsgpdocs#261]
The TenantConfiguration.xml default location is incorrect.  Recently went through a new GP Web Components installation (GP 18.3 version) and the TenantConfiguration.xml file is located in the C:\Program Files\Microsoft Dynamics\GP Web Components\SessionCentral directory and not the C:\Program Files\Microsoft Dynamics\GP Web Components\GPweb directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07c0ff83-09ba-c0fa-89ce-588d4c4fa622
* Version Independent ID: 97fe76f7-2869-dfb2-93f4-d4bf2507ed65
* Content: [Manage the logging for Dynamics GP web components - Dynamics GP](https://docs.microsoft.com/en-us/dynamics-gp/web-components/logging)
* Content Source: [dynamics-gp/web-components/logging.md](https://github.com/MicrosoftDocs/msftdynamicsgpdocs/blob/live/dynamics-gp/web-components/logging.md)
* Product: **dynamics-gp**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! This will be fixed in the next doc update.
