### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by walvis79** [MicrosoftDocs/msftdynamicsgpdocs#264]
Hello team, I went over this article trying to find help and I found a broken link under the section eSupport 
"Available at https://mbs.microsoft.com/support"

Error: We are sorry, the page you requested cannot be found

Thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aa4266d-d435-bdca-0db4-7a77bb2837de
* Version Independent ID: 5bf0b00c-5928-8921-0d20-459e2c615ca9
* Content: [Welcome to Dynamics GP - Dynamics GP](https://docs.microsoft.com/en-us/dynamics-gp/)
* Content Source: [dynamics-gp/index.md](https://github.com/MicrosoftDocs/msftdynamicsgpdocs/blob/live/dynamics-gp/index.md)
* Product: **dynamics-gp**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! We are in process of updating all links that currently point to  https://mbs.microsoft.com/support and related sites as they are being deprecated. You can find most of the content here: https://docs.microsoft.com/en-us/dynamics/s-e/gp/msdgpsupboundariesamericas_425
