### ISSUE TITLE
Incorrect Screen Shot in "Verify the web client installation" section...

### ISSUE THREAD

**Issue by n2aQFc8** [MicrosoftDocs/msftdynamicsgpdocs#343]
In the section - Verify the web client installation - you include the screenshot previously shown for configuring the GP Service... confusing and in the wrong place... should be removed and the correct screenshot (what a user sees when the load the URL) should be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f9f80af-ed53-20c4-54b5-9bdc736161b2
* Version Independent ID: 1275f553-266f-82d1-dd71-068f7abb5c78
* Content: [Installing on a single computer - Dynamics GP](https://docs.microsoft.com/en-us/dynamics-gp/web-components/single-machine-installation)
* Content Source: [dynamics-gp/web-components/single-machine-installation.md](https://github.com/MicrosoftDocs/msftdynamicsgpdocs/blob/live/dynamics-gp/web-components/single-machine-installation.md)
* Product: **dynamics-gp**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by jswymer** [comment]
Thanks for the feedback! This has been addressed in the help.
