### ISSUE TITLE
reporting 2 dead links in the Microsoft Dynamics GP Crashes after an Office Update section

### ISSUE THREAD

**Issue by DotGreto** [MicrosoftDocs/msftdynamicsgpdocs#423]
[Enter feedback here]
https://docs.microsoft.com/en-us/dynamics-gp/installation/email-troubleshooting-guide#microsoft-dynamics-gp-crashes-after-an-office-update

reporting 2 dead links in the Microsoft Dynamics GP Crashes after an Office Update section

For more information regarding the cause of this issue, see **this blog post** and **blog post** about Microsoft’s stance on the solutions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc16b44b-9036-8b6f-835f-1bf1d0d75189
* Version Independent ID: c70f236d-77d3-1d9c-7192-f9f58cbc9be4
* Content: [Dynamics GP Email Troubleshooting Guide - Dynamics GP](https://docs.microsoft.com/en-us/dynamics-gp/installation/email-troubleshooting-guide)
* Content Source: [dynamics-gp/installation/email-troubleshooting-guide.md](https://github.com/MicrosoftDocs/msftdynamicsgpdocs/blob/live/dynamics-gp/installation/email-troubleshooting-guide.md)
* Product: **dynamics-gp**
* GitHub Login: @theley502
* Microsoft Alias: **theley**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! The links have been fixed in today's doc update.
