### ISSUE TITLE
Typo in Transaction Level heading

### ISSUE THREAD

**Issue by AonCLBI** [MicrosoftDocs/msftdynamicsgpdocs#576]
There is a typo in the following heading:
>>Transaction Level Pot through GL without Printing GL Posting Journal
"Pot" should be "Post"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4bd7c983-9b07-55c6-0d9a-15abdd6e1bfe
* Version Independent ID: 4bd7c983-9b07-55c6-0d9a-15abdd6e1bfe
* Content: [What's new in Dynamics GP in October 2022 - Dynamics GP](https://learn.microsoft.com/en-us/dynamics-gp/whats-new/version-october-2022)
* Content Source: [dynamics-gp/whats-new/version-october-2022.md](https://github.com/MicrosoftDocs/msftdynamicsgpdocs/blob/live/dynamics-gp/whats-new/version-october-2022.md)
* Product: **dynamics-gp**
* GitHub Login: @theley502
* Microsoft Alias: **theley**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! we'll try to get this fixed later this week. However, since you know what is wrong, you might want to suggest the fix yourself as described here: https://learn.microsoft.com/en-us/dynamics-gp/#contributions-to-the-dynamics-gp-content

**Comment by jswymer** [comment]
Thanks for the feedback! The heading has been fixed and an update will be published soon.
