### ISSUE TITLE
Does "managed instance of Azure SQL Database" refer to Azure SQL Managed Instance?

### ISSUE THREAD

**Issue by WyattBest** [MicrosoftDocs/msftdynamicsgpdocs#578]
It's unclear if the sentence "Microsoft Dynamics GP cannot use a managed instance of Azure SQL Database" is referring to the Azure product Microsoft.AzureSQL or to Microsoft.SQLManagedInstance or to both.

I was trying to determine if it's possible to use Dynamics GP and Management Reporter with Azure SQL Managed Instance, which offers many more features than Azure SQL.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28600323-7a5d-1706-a7f0-413a113b7663
* Version Independent ID: 28600323-7a5d-1706-a7f0-413a113b7663
* Content: [Microsoft Dynamics GP on Microsoft Azure - Dynamics GP](https://learn.microsoft.com/en-us/dynamics-gp/installation/microsoftazureandgp)
* Content Source: [dynamics-gp/installation/MicrosoftAzureandGP.md](https://github.com/MicrosoftDocs/msftdynamicsgpdocs/blob/live/dynamics-gp/installation/MicrosoftAzureandGP.md)
* Product: **dynamics-gp**
* GitHub Login: @theley502
* Microsoft Alias: **theley**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback!
As you can see in the system requirements for Dynamics GP, only SQL Server is supported: 
https://learn.microsoft.com/en-us/dynamics-gp/upgrade/system-requirements#database-configuration-changes
