### ISSUE TITLE
Intercompany setup missing key "Setup" screen shots

### ISSUE THREAD

**Issue by vordesigns** [MicrosoftDocs/msftdynamicsgpdocs#589]
Intercompany setup missing key "Setup" screen shots

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8d65e421-757f-fd6c-146d-681b8a65d3d8
* Version Independent ID: 07b02815-c7fe-5e59-ecdf-7947f54b9061
* Content: [Intercompany Processing in Dynamics GP - Dynamics GP](https://learn.microsoft.com/en-us/dynamics-gp/financials/intercompanyprocessing)
* Content Source: [dynamics-gp/financials/IntercompanyProcessing.md](https://github.com/MicrosoftDocs/msftdynamicsgpdocs/blob/live/dynamics-gp/financials/IntercompanyProcessing.md)
* Product: **dynamics-gp**
* GitHub Login: @theley502
* Microsoft Alias: **theley**

**Comment by jswymer** [comment]
Thanks for the feedback! This has been addressed in the help.
