### ISSUE TITLE
Review doc for errors

### ISSUE THREAD

**Issue by msftblake** [MicrosoftDocs/msftdynamicsgpdocs#616]
You have a number of spelling and grammatical errors on this page unbecoming of an official Microsoft document.

Under this heading, you have "Server" written out as SErver: https://learn.microsoft.com/en-us/dynamics-gp/installation/microsoftazureandgp#configuring-microsoft-sql-server

Under this heading, you have "Machines" written as Machiens: https://learn.microsoft.com/en-us/dynamics-gp/installation/microsoftazureandgp#creating-virtual-machiens

Please re-review document for accuracy.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28600323-7a5d-1706-a7f0-413a113b7663
* Version Independent ID: 28600323-7a5d-1706-a7f0-413a113b7663
* Content: [Microsoft Dynamics GP on Microsoft Azure - Dynamics GP](https://learn.microsoft.com/en-us/dynamics-gp/installation/microsoftazureandgp)
* Content Source: [dynamics-gp/installation/MicrosoftAzureandGP.md](https://github.com/MicrosoftDocs/msftdynamicsgpdocs/blob/live/dynamics-gp/installation/MicrosoftAzureandGP.md)
* Product: **dynamics-gp**
* GitHub Login: @theley502
* Microsoft Alias: **theley**

**Comment by theley502** [comment]
completed updates

**Comment by theley502** [comment]
completed updates
